api_token_env: CROWDIN_TOKEN
project_id_env: CROWDIN_FACTORIO_MODS_ID
preserve_hierarchy: true

files:
  - source: /locale/en/QuickbarTemplates.cfg
    dest: QuickbarTemplates/QuickbarTemplates.ini
    translation: /locale/%two_letters_code%/%original_file_name%
    type: ini
